### ISSUE TITLE
Zipball URL is More Useful 😁

### ISSUE THREAD

**Issue by drinfernoo** [ikidd/seren.theme.old_source_select#1]
The zipball URL you've included on your readme can actually just be copied in when you install a theme from "Web location". No need to manually download the zip and browse to it 👍

**Comment by ikidd** [comment]
I didn't think you could paste anything in Kodi dialogs. I'll have to try that out.

**Comment by drinfernoo** [comment]
You sure can! Also most remote apps like Kore, Yatse, or even Android TV Remote, let you send text directly to Kodi (or your device in general, in the Android TV instance).

The greater point is that that URL is directly to the zip file, so you can input it directly without the need to download it first.
